"""Pydantic models describing every kind of content Educhain can generate."""

from .base_models import BaseQuestion, QuestionList
from .qna_models import (
    MultipleChoiceQuestion,
    ShortAnswerQuestion,
    TrueFalseQuestion,
    FillInBlankQuestion,
    MCQList,
    ShortAnswerQuestionList,
    TrueFalseQuestionList,
    FillInBlankQuestionList,
    Option,
    MCQMath,
    MCQListMath,
    GraphInstruction,
    VisualMCQ,
    VisualMCQList,
    SolvedDoubt,
    SpeechInstructions,
    BulkMCQ,
    BulkMCQList,
    BulkShortAnswerQuestion,
    BulkShortAnswerQuestionList,
    BulkTrueFalseQuestion,
    BulkTrueFalseQuestionList,
    BulkFillInBlankQuestion,
    BulkFillInBlankQuestionList,
)
from .content_models import (
    ContentElement,
    SubTopic,
    MainTopic,
    LessonPlan,
    Flashcard,
    FlashcardSet,
    StudyGuide,
    CaseStudy,
    CareerConnections,
    PodcastSegment,
    PodcastScript,
    PodcastContent,
)
from .pedagogy_models import (
    BloomsTaxonomyContent,
    SocraticQuestioningContent,
    ProjectBasedLearningContent,
    FlippedClassroomContent,
    InquiryBasedLearningContent,
    ConstructivistContent,
    GamificationContent,
    PeerLearningContent,
)

__all__ = [
    # base / qna
    "BaseQuestion",
    "QuestionList",
    "MultipleChoiceQuestion",
    "ShortAnswerQuestion",
    "TrueFalseQuestion",
    "FillInBlankQuestion",
    "MCQList",
    "ShortAnswerQuestionList",
    "TrueFalseQuestionList",
    "FillInBlankQuestionList",
    "Option",
    "MCQMath",
    "MCQListMath",
    "GraphInstruction",
    "VisualMCQ",
    "VisualMCQList",
    "SolvedDoubt",
    "SpeechInstructions",
    "BulkMCQ",
    "BulkMCQList",
    "BulkShortAnswerQuestion",
    "BulkShortAnswerQuestionList",
    "BulkTrueFalseQuestion",
    "BulkTrueFalseQuestionList",
    "BulkFillInBlankQuestion",
    "BulkFillInBlankQuestionList",
    # content
    "ContentElement",
    "SubTopic",
    "MainTopic",
    "LessonPlan",
    "Flashcard",
    "FlashcardSet",
    "StudyGuide",
    "CaseStudy",
    "CareerConnections",
    "PodcastSegment",
    "PodcastScript",
    "PodcastContent",
    # pedagogy
    "BloomsTaxonomyContent",
    "SocraticQuestioningContent",
    "ProjectBasedLearningContent",
    "FlippedClassroomContent",
    "InquiryBasedLearningContent",
    "ConstructivistContent",
    "GamificationContent",
    "PeerLearningContent",
]
